### ISSUE TITLE
Change bitstream

### ISSUE THREAD

**Issue by 5XS** [CrazorTheCat/BSDS-V41#2]
`bitstream` is Python 2.7 only, do not install it with Py 3.6.

**Comment by CrazorTheCat** [comment]
if you still have problem with installing it make sure numpy is also installed, since its required by bitstream module

**Comment by 5XS** [comment]
> if you still have problem with installing it make sure numpy is also installed, since its required by bitstream module

numpy is installed

**Comment by CrazorTheCat** [comment]
then retry installing bitstream i have python 3.9 and it work well

**Comment by 5XS** [comment]
> then retry installing bitstream i have python 3.9 and it work well

I've tried
