### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EvgeniiKornev1** [CrazorTheCat/BSDS-V41#3]
login failed . Please try again later (different numbers) Please tell me what to do?

**Comment by CrazorTheCat** [comment]
you need to change the ip address in the apk please read the readme file to know more

**Comment by EvgeniiKornev1** [comment]
> you need to change the ip address in the apk please read the readme file to know more

Hi, when I edit the APK, I write that it was not possible to process the package

**Comment by CrazorTheCat** [comment]
because you need to sign it after editing
