### ISSUE TITLE
DataBase bug

### ISSUE THREAD

**Issue by Mops2008wer** [CrazorTheCat/BSDS-V41#5]
The first time I managed to log into the server, but when I changed the value in the database, I got this error. After that I uninstalled the server and installed again, but the error persisted. I even started a clean server on another disk and reinstalled the brawl, but the error did not fix.
![Screenshot_784](https://user-images.githubusercontent.com/78369368/147873106-3ed05c63-8f18-46a5-8bb5-70273544ac89.png)

**Comment by CrazorTheCat** [comment]
well you need a special program to edit it
i suggest this https://sqlitebrowser.org/

**Comment by ServerBSvvv** [comment]
![image](https://user-images.githubusercontent.com/77868876/148341873-b2825831-ed82-4aee-9d05-7c9ed6c75b6b.png)
pygame? xD
