### ISSUE TITLE
New Server

### ISSUE THREAD

**Issue by Sinix0** [CrazorTheCat/BSDS-V41#6]
Hello, I have not seen any server in C±±. Can you at least enter the main menu? Please:)

**Comment by qwwe33dev** [comment]
wdym

**Comment by CrazorTheCat** [comment]
you want me to do a server in c++ publicly?

**Comment by Sinix0** [comment]
Yes if it is possible. At least the main menu.

**Comment by Sinix0** [comment]
You will be the first to make a server on c++

**Comment by CrazorTheCat** [comment]
i could but i kinda got bored but maybe in futur i could try that it would be a fun experience

**Comment by Sinix0** [comment]
I hope you are the best
